### ISSUE TITLE
Cannot extract kernel package

### ISSUE THREAD

**Issue by mefmund** [adoconnection/SevenZipExtractor#40]
I'm trying to extract tar.xz package downloaded from kernel.org (https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.4.12.tar.xz)
ArchiveFile object has one entry but all fields are null
![image](https://user-images.githubusercontent.com/23142365/72412619-1830c100-376e-11ea-89a6-af09526ad19e.png)

**Comment by adoconnection** [comment]
its because tar.xz is actually two archive files:
1. tar packs all files and folders into one so called tarball file without compression
2. xz does compression

so to unpack you need to perform same operations in reverse:

```cs
using (ArchiveFile archiveFileXz = new ArchiveFile(@"Linux-5.4.12.tar.xz"))
{
    MemoryStream memoryStream = new MemoryStream();
    archiveFileXz.Entries[0].Extract(memoryStream);

    using (ArchiveFile archiveFileTar = new ArchiveFile(memoryStream, SevenZipFormat.Tar))
    {
        foreach (Entry entry in archiveFileTar.Entries)
        {
            Console.WriteLine(entry.FileName);
        }
    }
}
```

this code is somewhat unefficient as it creates unpacked file copy in a memory, but it is ok for small files

**Comment by adoconnection** [comment]
started a wiki: https://github.com/adoconnection/SevenZipExtractor/wiki/Extract-tar.gz,-tag.xz
