### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Onkelborg** [adoconnection/SevenZipExtractor#6]
Could you clarify what license this project uses?

(I can't find it anywhere - the code project article this project emerged from is MIT licensed, but I can't take that for granted for this project.)

**Comment by adoconnection** [comment]
Hi, I've updated readme.md

**Comment by toddjames** [comment]
@adoconnection Thanks for the library and thanks for choosing the MIT license.

Just a suggestion: you should include a `LICENSE` file in your repo. This is standard practice and if you follow the [GitHub instructions to do so](https://help.github.com/articles/adding-a-license-to-a-repository/), you'll end up with your project tagged as MIT-licensed on the GitHub UI.

I almost opened an identical issue to this one because I didn't see the `LICENSE` file.

**Comment by adoconnection** [comment]
OK, thank you for feedback

**Comment by adoconnection** [comment]
@toddjames done
https://github.com/adoconnection/SevenZipExtractor/blob/master/LICENSE
